"use strict";

$.$setTemplate( "main", o => [
	$.$div( { id: "title" },
		$.$span( null, "Gammes" ),
		$.$span( null, "by GridSound" ),
	),
	$.$div( { id: "form" },
		$.$div( null,
			$.$label( null, $.$input( { name: "majorMinor", type: "radio", value: "major", checked: o.majorMinor === "major" } ), $.$span( null, "Major" ) ),
			$.$label( null, $.$input( { name: "majorMinor", type: "radio", value: "minor", checked: o.majorMinor === "minor" } ), $.$span( null, "Minor" ) ),
		),
		$.$div( null,
			$.$label( null, $.$input( { name: "notation", type: "radio", value: "doremi", checked: o.notation === "doremi" } ), $.$span( null, "Do, Ré, Mi, ..." ) ),
			$.$label( null, $.$input( { name: "notation", type: "radio", value: "CDE", checked: o.notation === "CDE" } ), $.$span( null, "C, D, E, ..." ) ),
		),
		$.$div( null,
			$.$label( null, $.$input( { name: "diezeBemol", type: "radio", value: "♯", checked: o.diezeBemol === "♯" } ), $.$span( null, "♯" ) ),
			$.$label( null, $.$input( { name: "diezeBemol", type: "radio", value: "♭", checked: o.diezeBemol === "♭" } ), $.$span( null, "♭" ) ),
		),
	),
	$.$div( { id: "scalesGraph", "data-scale-m": majorMinor },
		$.$div( { id: "scalesGraphPadding" },
			$.$div( { id: "scalesGraphInn" },
				$.$div( { id: "circle-ext" } ),
				$.$div( { id: "keys" },
					$.$div( { class: "key", style: "--keyInd:  0", "data-key": 0 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  1", "data-key": 1 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  2", "data-key": 2 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  3", "data-key": 3 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  4", "data-key": 4 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  5", "data-key": 5 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  6", "data-key": 6 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  7", "data-key": 7 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  8", "data-key": 8 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd:  9", "data-key": 9 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd: 10", "data-key": 10 }, $.$span()),
					$.$div( { class: "key", style: "--keyInd: 11", "data-key": 11 }, $.$span()),
				),
				$.$div( { id: "svg-wrap" },
					$.$elem( "svg", { id: "svg", viewBox: "0 0 100 100" },
						$.$elem( "polygon", { id: "polyMajor", points: "50,0 93,25 93,75 75,93 25,93 0,50 25,7" } ),
						$.$elem( "polygon", { id: "polyMinor", points: "50,0 93,25 100,50 75,93 25,93 7,75 7,25" } ),
					)
				),
				$.$button( { id: "playBtn", icon: "play" } ),
			),
		),
	),
	$.$elem( "div", { id: "foot" },
		$.$elem( "span", { id: "copyright" },
			`© ${ new Date().getFullYear() } `,
			$.$link( { href: "https://gridsound.com" }, "gridsound.com" ),
			" all rights reserved",
		),
	),
] );
